---
version: "3.4"
services:
  Kali:
    image: sadry/sadry:tp_pen_kali
    container_name: kali
    stdin_open: true
    tty: true
    ports:
      - 9020:8080
      - 9021:5900
    networks:
      networkpentest:
        ipv4_address: 172.16.0.10
  samba:
    container_name: samba
    image: hichigari/samba
    networks:
      networkpentest:
        ipv4_address: 172.16.0.11
    ports:
      - 1370:137/udp
      - 1380:138/udp
      - 1390:139/tcp
      - 4450:445/tcp
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    tty: true
    
  nessus:
    image: tenableofficial/nessus
    restart: always
    container_name: nessus
    ports:
      - 8834:8834
    networks:
      networkpentest:
        ipv4_address: 172.16.0.12
  wordpress:
    build: .
    ports:
      - 31337:80
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 31338:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql
  wp-cli:
    image: wordpress:cli-php7.1
    environment:
      - APACHE_RUN_USER="www-data"
      - APACHE_RUN_GROUP="www-data"
    depends_on:
      - mysql
    volumes:
      - wp:/var/www/html:rw
      - ./bin/install-wp.sh:/usr/local/bin/install-wp:ro
      
  tomcat:
    image: vulhub/tomcat:8.0
    container_name: tomcat
    volumes:
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
      - ./context.xml:/usr/local/tomcat/webapps/host-manager/META-INF/context.xml
    ports:
      - 8080:8080
    networks:
      networkpentest:
        ipv4_address: 172.16.0.13
        
  dvwa_web:
    container_name: dvwa
    image: cytopia/dvwa:php-${PHP_VERSION:-8.1}
    restart: unless-stopped
    ports:
      - ${LISTEN_PORT:-8000}:80
    networks:
      networkpentest:
        ipv4_address: 172.16.0.14
    environment:
      - RECAPTCHA_PRIV_KEY=${RECAPTCHA_PRIV_KEY:-}
      - RECAPTCHA_PUB_KEY=${RECAPTCHA_PUB_KEY:-}
      - SECURITY_LEVEL=${SECURITY_LEVEL:-medium}
      - PHPIDS_ENABLED=${PHPIDS_ENABLED:-0}
      - PHPIDS_VERBOSE=${PHPIDS_VERBOSE:-0}
      - PHP_DISPLAY_ERRORS=${PHP_DISPLAY_ERRORS:-0}
      - MYSQL_HOSTNAME=dvwa_db
      - MYSQL_DATABASE=dvwa
      - MYSQL_USERNAME=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
  dvwa_db:
    image: mariadb:10.1
    hostname: dvwa_db
    volumes:
      - dvwa_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dvwa
      MYSQL_USER: dvwa
      MYSQL_PASSWORD: p@ssw0rd
    restart: unless-stopped
    networks:
      networkpentest:
        ipv4_address: 172.16.0.15
volumes:
  wp: {}
  db: {}
  dvwa_db_data: null
networks:
  networkpentest:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
